### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by TheRedDemons** [SlavyanDesu/BocchiBot#277]
**Question**
What would you like to ask?
if i write ' npm i or npm install' like this please help me
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/YogaSakti/video-url-link.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by Baguettou** [comment]
I'm not really sure how to solve that problem but I found [this](https://docs.github.com/es/github/authenticating-to-github/error-permission-denied-publickey)  and [this.](https://gist.github.com/adamjohnson/5682757)

Hope this help you ^ - ^.

**Comment by VideFrelan** [comment]
Hello, please download and install gitbash [here](https://git-scm.com/downloads)

**Comment by SlavyanDesu** [comment]
Try the solutions above. It should be worked.

**Comment by DwiP27** [comment]
aku udah install ini tapi masih bermasalah

**Comment by DwiP27** [comment]
> aku udah install ini tapi masih bermasalah

@SlavyanDesu  help @VideFrelan

**Comment by DwiP27** [comment]
**HELP ME**

**Comment by Baguettou** [comment]
Hi, try:
1. `npm cache clean` and after `npm install` (If needed use `npm cache clean --force`)
2. `npm config set registry http://registry.npmjs.org/` (change to HTTP) and after `npm install`
or
3. `npm config set registry https://registry.npmjs.org/` (change to HTTPS) and after `npm install`

Let us know how everything goes, and have a nice day. :D

**Comment by DwiP27** [comment]
> Hi, try:
> 
> 1. `npm cache clean` and after `npm install` (If needed use `npm cache clean --force`)
> 2. `npm config set registry http://registry.npmjs.org/` (change to HTTP) and after `npm install`
>    or
> 3. `npm config set registry https://registry.npmjs.org/` (change to HTTPS) and after `npm install`
> 
> Let us know how everything goes, and have a nice day. :D

C:\Users\DWI PUTRA\BocchiBot>npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has bee
n deprecated because it extends the now deprecated request package, see https://
github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://git
hub.com/request/request/issues/3142
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to http://registry.npmjs.org/mimic-response/-/mimic-response-3.
1.0.tgz failed, reason: Socket timeout

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DWI PUTRA\AppData\Local\npm-cache\_logs\2021-05-20T12_26_3
9_542Z-debug.log

C:\Users\DWI PUTRA\BocchiBot>

**Comment by Baguettou** [comment]
Ok, change the version of open-WA directly from `packages.json` file

![imagen_2021-05-20_093809](https://user-images.githubusercontent.com/68337546/118998464-16bd6d00-b94f-11eb-8ca2-e7cd0f80bd3b.png)

Then delete the `node_modules` directory again and try this:

1. `npm cache clean -f`
2. `npm install -g n`
3. `n stable`

Maybe that will work?

**Comment by DwiP27** [comment]
> 2\. npm install -g n

thanks for help me, but 

C:\Users\DWI PUTRA\BocchiBot>npm install -g n
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@7.2.2: wanted {"os":"!win32"} (curren
t: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DWI PUTRA\AppData\Local\npm-cache\_logs\2021-05-20T18_36_5
7_558Z-debug.log

C:\Users\DWI PUTRA\BocchiBot>
